/*
 *  profile_depend.h (x86)
 *  System profile information for x86 micro T-Kernel
 */

#ifndef __SYS_CORE_PROFILE_DEPEND_H__
#define __SYS_CORE_PROFILE_DEPEND_H__

#include <machine.h>
#include <config.h>

#ifdef __cplusplus
extern "C" {
#endif

#define TK_STDTK            FALSE
#define TK_MICROTK          TRUE
#define TK_ALLOW_MISALIGN   (ALLOW_MISALIGN)
#define TK_BIGENDIAN        (BIGENDIAN)
#define TK_VIRTUAL_ADDRESS  (VIRTUAL_ADDRESS)
#define TK_VIRTUAL_MEMORY   FALSE
#define TK_TRAP_SVC         (USE_TRAP)
#define TK_HAS_DOUBLEWORD   FALSE
#define TK_SUPPORT_SERCD    FALSE
#define TK_HAS_SYSSTACK     FALSE
#define TK_SUPPORT_FPU      FALSE
#define TK_SUPPORT_COP0     FALSE
#define TK_SUPPORT_COP1     FALSE
#define TK_SUPPORT_COP2     FALSE
#define TK_SUPPORT_COP3     FALSE
#define TK_SUPPORT_RESOURCE FALSE
#define TK_SUPPORT_USERBUF  TRUE
#define TK_SUPPORT_AUTOBUF  TRUE
#define TK_SUPPORT_SLICETIME FALSE
#define TK_SUPPORT_TASKINF  FALSE
#define TK_SUPPORT_USEC     FALSE
#define TK_SUPPORT_TASKSPACE FALSE
#define TK_SUPPORT_TASKEVENT FALSE
#define TK_SUPPORT_DISWAI   FALSE
#define TK_SUPPORT_REGOPS   TRUE
#define TK_SUPPORT_ASM      FALSE
#define TK_SUPPORT_DSNAME   (USE_OBJECT_NAME)
#define TK_SUPPORT_TASKEXCEPTION FALSE
#define TK_SUPPORT_LOWPOWER FALSE
#define TK_SUPPORT_SSYEVENT FALSE
#define TK_SUPPORT_LARGEDEV FALSE
#define TK_SUPPORT_INTCTRL  TRUE
#define TK_HAS_ENAINTLEVEL  FALSE
#define TK_SUPPORT_CPUINTLEVEL FALSE
#define TK_SUPPORT_CTRLINTLEVEL FALSE
#define TK_SUPPORT_INTMODE  FALSE
#define TK_SUPPORT_SYSCONF  FALSE
#define TK_SUPPORT_IOPORT   TRUE
#define TK_SUPPORT_MICROWAIT FALSE
#define TK_SUPPORT_CACHECTRL FALSE
#define TK_SUPPORT_WBCACHE  FALSE
#define TK_SUPPORT_WTCACHE  FALSE
#define TK_SUPPORT_SYSMEMBLK FALSE
#define TK_SUPPORT_MEMLIB   FALSE
#define TK_SUPPORT_ADDRSPACE FALSE
#define TK_SUPPORT_PTIMER   FALSE
#define TK_SUPPORT_DBGSPT   (USE_DBGSPT)

#define CFN_VER_MAJOR       2
#define CFN_VER_MINOR       0
#define TK_SPECVER_MAJOR    (CFN_VER_MAJOR)
#define TK_SPECVER_MINOR    (CFN_VER_MINOR)
#define TK_SPECVER          ((TK_SPECVER_MAJOR << 8) | TK_SPECVER_MINOR)

#define TK_MAX_TSKPRI       (MAX_PRI)
#define TK_WAKEUP_MAXCNT    (+2147483647L)
#define TK_SEMAPHORE_MAXCNT (+2147483647L)
#define TK_SUSPEND_MAXCNT   (+2147483647L)

#define TK_MEM_RNG0         0
#define TK_MEM_RNG1         0
#define TK_MEM_RNG2         0
#define TK_MEM_RNG3         0
#define TK_MAX_PTIMER       0

#ifdef __cplusplus
}
#endif

#endif /* __SYS_CORE_PROFILE_DEPEND_H__ */
