#!/bin/bash
# ---------------------------------------------------------------------------
# run_yield.sh — host cert for the COOPERATIVE-YIELD DMN fix
#                (docs/architecture/cooperative-yield-plan.md;
#                 arch/common/llm/student_shell.c).
#
# Builds the cert against the REAL production student_shell.c (#included so its
# static sliced-consolidation internals + the file-static cursor are exercised)
# plus the real student.c math, and runs:
#
#   [yield-byte-identical]  sliced (w/ interleaved pure-read inference) == the
#                           all-at-once run, FULL st_save blob memcmp == 0.
#   [yield-responsive]      the production student_dmn_consolidate() state
#                           machine advances <= K passes/call, the cumulative
#                           pass count is unchanged (not skipped), and the final
#                           blob/loss == the all-at-once reference.
#
# FALSIFIER: a second build with -DYIELD_DISABLE runs the whole batch per call.
# The cert MUST go RED there ([yield-responsive] (a) fails) — proof of teeth.
# This script PASSes only if the normal build is GREEN AND the falsifier is RED.
#
#   ./run_yield.sh
# Exit 0 = fix present & certified.
# ---------------------------------------------------------------------------
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
CC="${CC:-cc}"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Links the REAL cradle.c (lesson ring + ingest + the freeze gate) so Cert C
# exercises the genuine mid-batch-deferral path, plus student.c (the math).
# dlb.c: student_shell.c (#included by the test) now routes the chat-generate
# verb through the DLB search×verify feeder (Wave-D2: dlb_answer /
# dlb_compound_enqueue / dlb_gate_vexact / dlb_compound_{pending,distill,gc}).
# Those live in the self-contained arch/common/llm/dlb.c (only dlb.h + stdlib,
# no kernel surface), so the yield cert must link it or the NDK-clean host link
# breaks with `undefined reference to dlb_*`. The yield cert never DRIVES the
# chat verb (it exercises student_dmn_consolidate + st_save byte-identity only),
# but the symbols must still resolve at link time.
SRC="$HERE/student_yield_test.c $ROOT/arch/common/llm/student.c $ROOT/arch/common/llm/cradle.c $ROOT/arch/common/llm/dlb.c"

# student_shell.c (#included by the test) now references the 良心 floor
# (conscience_check / conscience_on_refuse) and the Frontier Mouth self-test
# (frontier_self_test) UNCONDITIONALLY — but ONLY on the chat-generate and
# `student frontier` verbs, which this cooperative-YIELD cert never drives (it
# exercises student_dmn_consolidate + st_save byte-identity only; cradle.c's
# conscience calls are behind CRADLE_HAS_CONSCIENCE, not set here). The REAL
# conscience.c/frontier.c drag in the whole kernel surface (pfs_* / galaxy_emit
# / lm_self_* / drpc_my_node / intero_note / sio_send_frame), which does NOT
# belong in this focused native-cc host cert. The conscience gate has its OWN
# certs ([conscience-*]/[law-*] in the ump-x86_64 job); here we only satisfy the
# linker with an ALLOW stub, provably off the certified path. Generated fresh in
# $WORK so nothing is committed.
STUB="$WORK/yield_cons_frontier_stub.c"
cat > "$STUB" <<'EOF'
/* auto-generated by run_yield.sh — link-only stubs for symbols student_shell.c
 * references on the chat/frontier verbs, which the cooperative-yield cert never
 * drives. conscience returns CONS_ALLOW (0). NOT the conscience cert (that is
 * [conscience-*]/[law-*]); this cert certifies yield byte-identity only. */
int conscience_check(unsigned char site, const void *q) { (void)site; (void)q; return 0; }
const char *conscience_on_refuse(unsigned char site, int verdict) { (void)site; (void)verdict; return ""; }
void frontier_self_test(void (*emit)(const char *)) { (void)emit; }
EOF
SRC="$SRC $STUB"
CFLAGS="-std=c11 -O1 -Wall -Wextra -ffp-contract=off"

echo "[build] compiling cooperative-yield cert (fix ON) ..."
# shellcheck disable=SC2086
"$CC" $CFLAGS $SRC -lm -o "$WORK/yield_on" || { echo "[build] FAILED"; exit 1; }

echo "[build] compiling falsifier (-DYIELD_DISABLE) ..."
# shellcheck disable=SC2086
"$CC" $CFLAGS -DYIELD_DISABLE $SRC -lm -o "$WORK/yield_off" \
    || { echo "[build] falsifier FAILED"; exit 1; }

echo ""
echo "=== fix ON (must PASS) ==="
( cd "$ROOT" && "$WORK/yield_on" ); ON_RC=$?

echo ""
echo "=== falsifier -DYIELD_DISABLE (must FAIL = RED, proving teeth) ==="
( cd "$ROOT" && "$WORK/yield_off" ); OFF_RC=$?

echo ""
if [ "$ON_RC" -eq 0 ] && [ "$OFF_RC" -ne 0 ]; then
    echo "[result] PASS  (fix GREEN, falsifier RED — the cert has teeth)"
    exit 0
fi
echo "[result] FAIL  (fix rc=$ON_RC [want 0], falsifier rc=$OFF_RC [want non-0])"
exit 1
