/*
 * MainActivity.kt — the SETTINGS layer (3-layer-discover wave).
 *
 * Three clean, FINDABLE layers (0.6.3 feedback: they were undiscoverable):
 *
 * Layer 1 (GalaxyActivity): the sky + a VISIBLE ⚙ gear into this screen.
 *
 * Layer 2 (THIS screen, EXTRA_ADVANCED): a clear "Settings" header and the
 * FRIENDLY controls shown DIRECTLY (no "Advanced" tap to reveal): battery-safe
 * toggle (PKernelService.PREF_CHARGE_ONLY) · battery floor · Wi-Fi only ·
 * start-on-boot · "View introduction again" · the app version · ONE labelled
 * "Engineer / advanced" door. NO raw relay host/port/hex-key here — the
 * technical fleet fields moved to the engineer page.
 *
 * Layer 3 (LogActivity): the raw stdout tail + node internals + module
 * versions + the technical Fleet/relay fields — jargon lives there only.
 *
 * The no-form default path (NOT EXTRA_ADVANCED) is unchanged: light the star
 * from prefs and jump straight to the galaxy. The node id / relay values are
 * read from the "ump" prefs (where the engineer page and the service both
 * persist them) rather than from on-screen fields.
 *
 * All visible strings come from values-<locale>/strings.xml (generated by
 * tools/android/gen_strings.py for the manifesto languages), so the screen
 * speaks the user's language from the first frame, falling back to English.
 */

package io.pkernel

import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Intent
import android.os.Build
import android.os.Bundle
import android.view.View
import android.widget.Button
import android.widget.SeekBar
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import androidx.appcompat.widget.SwitchCompat

class MainActivity : AppCompatActivity() {

    private lateinit var batterySafeSwitch: SwitchCompat
    private lateinit var floorLabel: TextView
    private lateinit var floorSeek: SeekBar
    private lateinit var wifiOnlySwitch: SwitchCompat
    private lateinit var startOnBootSwitch: SwitchCompat
    private lateinit var useGpuSwitch: SwitchCompat

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        ensureNotificationChannel()

        /* UX constitution (docs/product-soul.md): users don't care about
         * kernels. The DEFAULT path has no form — the node lights itself and
         * the first thing a person sees is the galaxy's own introduction (the
         * manifesto gate). This settings screen survives ONLY as the
         * "advanced" screen, reached from the ⋮ corner of the galaxy. */
        if (!intent.getBooleanExtra(EXTRA_ADVANCED, false)) {
            val prefs = getSharedPreferences(PREFS, MODE_PRIVATE)
            // first light: derive a STABLE id from a persistent per-install seed.
            val nodeId = ensureNodeId(prefs)
            startKernelWith(
                nodeId,
                prefs.getString(PREF_RELAY_HOST, "") ?: "",
                prefs.getInt(PREF_RELAY_PORT, 7400),
                prefs.getString(PREF_RELAY_KEY, "") ?: "")
            startActivity(Intent(this, GalaxyActivity::class.java).apply {
                putExtra(GalaxyActivity.EXTRA_NODE_ID, nodeId)
            })
            finish()
            return
        }

        setContentView(R.layout.activity_main)

        batterySafeSwitch = findViewById(R.id.switch_battery_safe)
        floorLabel        = findViewById(R.id.label_battery_floor)
        floorSeek         = findViewById(R.id.seek_battery_floor)
        wifiOnlySwitch    = findViewById(R.id.switch_wifi_only)
        startOnBootSwitch = findViewById(R.id.switch_start_on_boot)
        useGpuSwitch      = findViewById(R.id.switch_use_gpu)

        /* node id / relay live in prefs now (the engineer page edits them, the
         * service persists them). First run DERIVES a stable node id from a
         * persistent per-install random seed (N-0) instead of everyone being
         * "1" (honest bound: ids live in 1..63 — true uniqueness needs a
         * key-derived id, a named future wave). */
        val prefs = getSharedPreferences(PREFS, MODE_PRIVATE)
        ensureNodeId(prefs)

        /* Battery-safe toggle: bound to PKernelService.PREF_CHARGE_ONLY in the
         * "ump" prefs (default ON). Toggling persists; it takes effect at the
         * next gate check (powerAllowed()) — we do NOT touch the gate logic. */
        batterySafeSwitch.isChecked =
            prefs.getBoolean(PKernelService.PREF_CHARGE_ONLY, true)
        batterySafeSwitch.setOnCheckedChangeListener { _, checked ->
            getSharedPreferences(PREFS, MODE_PRIVATE).edit()
                .putBoolean(PKernelService.PREF_CHARGE_ONLY, checked).apply()
        }

        /* Battery floor SeekBar: range 10..50 step 5 (9 stops => max=8).
         * progress p maps to floor = FLOOR_MIN + p*FLOOR_STEP. The label shows
         * the live value; PREF_BATTERY_FLOOR is what powerAllowed() reads. The
         * pref persists; it takes effect at the next gate check — we do NOT
         * touch the pause/resume/JobScheduler logic, only the threshold value. */
        val savedFloor = prefs.getInt(PKernelService.PREF_BATTERY_FLOOR,
                                      PKernelService.BATTERY_FLOOR_PCT)
                             .coerceIn(FLOOR_MIN, FLOOR_MAX)
        floorSeek.progress = (savedFloor - FLOOR_MIN) / FLOOR_STEP
        floorLabel.text = getString(R.string.pref_floor_label, savedFloor)
        floorSeek.setOnSeekBarChangeListener(object : SeekBar.OnSeekBarChangeListener {
            override fun onProgressChanged(sb: SeekBar?, progress: Int, fromUser: Boolean) {
                val floor = FLOOR_MIN + progress * FLOOR_STEP
                floorLabel.text = getString(R.string.pref_floor_label, floor)
                getSharedPreferences(PREFS, MODE_PRIVATE).edit()
                    .putInt(PKernelService.PREF_BATTERY_FLOOR, floor).apply()
            }
            override fun onStartTrackingTouch(sb: SeekBar?) {}
            override fun onStopTrackingTouch(sb: SeekBar?) {}
        })

        /* WiFi-only toggle: PREF_WIFI_ONLY (default OFF). Takes effect at the
         * next gate check (runAllowed()); the service's NetworkCallback then
         * pauses/resumes the node as connectivity changes. */
        wifiOnlySwitch.isChecked = prefs.getBoolean(PKernelService.PREF_WIFI_ONLY, false)
        wifiOnlySwitch.setOnCheckedChangeListener { _, checked ->
            getSharedPreferences(PREFS, MODE_PRIVATE).edit()
                .putBoolean(PKernelService.PREF_WIFI_ONLY, checked).apply()
        }

        /* Start-on-boot toggle: PREF_START_ON_BOOT (default OFF). Read by
         * BootReceiver on ACTION_BOOT_COMPLETED. */
        startOnBootSwitch.isChecked =
            prefs.getBoolean(PKernelService.PREF_START_ON_BOOT, false)
        startOnBootSwitch.setOnCheckedChangeListener { _, checked ->
            getSharedPreferences(PREFS, MODE_PRIVATE).edit()
                .putBoolean(PKernelService.PREF_START_ON_BOOT, checked).apply()
        }

        /* Use-GPU toggle: PREF_USE_GPU (default OFF — honestly experimental and
         * matching the native gpu_set_enabled default). The toggle's ENABLED-ness
         * keys off CAPABILITY (Gpu.capable() — does a usable Vulkan device
         * EXIST?), NOT availability (Gpu.available() — capable AND already
         * switched ON). Using available() here deadlocked the UI: the flag
         * defaults OFF, so available() returned false, so the toggle was greyed,
         * so the user could never turn the flag ON — greyed because OFF, OFF
         * because greyed. capable() probes the hardware regardless of the flag.
         *
         * When capable: enable the toggle, set it from the stored pref, AND
         * re-apply that persisted state to native (setEnabled) on entry so a
         * saved ON survives a relaunch. On toggle: persist + setEnabled. This
         * wave only surfaces the flag; the mind still runs inference on the CPU
         * (GPU-3 wires the matmul). We do NOT touch the inference path. */
        val gpuCapable = PKernel.Gpu.capable()
        if (gpuCapable) {
            val gpuOn = prefs.getBoolean(PREF_USE_GPU, false)
            PKernel.Gpu.setEnabled(gpuOn)        // re-apply persisted pref to native
            useGpuSwitch.isChecked = gpuOn
            useGpuSwitch.isEnabled = true
            useGpuSwitch.setText(R.string.pref_use_gpu)
            useGpuSwitch.setOnCheckedChangeListener { _, checked ->
                getSharedPreferences(PREFS, MODE_PRIVATE).edit()
                    .putBoolean(PREF_USE_GPU, checked).apply()
                PKernel.Gpu.setEnabled(checked)
            }
        } else {
            /* No usable GPU on this device: greyed + honest label, never checked. */
            useGpuSwitch.isChecked = false
            useGpuSwitch.isEnabled = false
            useGpuSwitch.setText(R.string.pref_use_gpu_unavailable)
        }

        /* App version — read straight off the PackageManager so we never need
         * BuildConfig enabled. "yurikago <versionName>". */
        findViewById<TextView>(R.id.app_version).text =
            getString(R.string.app_version_fmt, appVersionName())

        findViewById<Button>(R.id.btn_start ).setOnClickListener { startKernel() }
        findViewById<Button>(R.id.btn_stop  ).setOnClickListener { stopKernel()  }
        findViewById<Button>(R.id.btn_galaxy).setOnClickListener { openGalaxy()  }
        findViewById<Button>(R.id.btn_engineer).setOnClickListener {
            startActivity(Intent(this, LogActivity::class.java))
        }
        findViewById<Button>(R.id.btn_reintro).setOnClickListener { replayIntro() }

        /* state, in human words: poll the star's window; swap 灯す/眠らせる
         * so the screen never asks you to light an already-shining star. */
        Thread({
            while (!isFinishing) {
                val id = currentNodeId()
                val lit = try {
                    java.net.Socket().use { sk ->
                        sk.connect(java.net.InetSocketAddress("127.0.0.1", 7800 + id - 1), 300); true }
                } catch (_: Throwable) { false }
                runOnUiThread {
                    findViewById<TextView>(R.id.star_status).text =
                        getString(if (lit) R.string.star_lit else R.string.star_dark)
                    findViewById<Button>(R.id.btn_start).visibility =
                        if (lit) View.GONE else View.VISIBLE
                    findViewById<Button>(R.id.btn_stop).visibility =
                        if (lit) View.VISIBLE else View.GONE
                }
                try { Thread.sleep(1200) } catch (_: InterruptedException) { return@Thread }
            }
        }, "star-status").apply { isDaemon = true; start() }
    }

    /** The persisted "ump" prefs — node id / relay are edited on the engineer
     *  page and persisted by the service; the Settings layer just reads them. */
    private fun currentNodeId(): Int =
        ensureNodeId(getSharedPreferences(PREFS, MODE_PRIVATE))

    /** "yurikago 0.6.3" — straight off the PackageManager (no BuildConfig). */
    private fun appVersionName(): String =
        try { packageManager.getPackageInfo(packageName, 0).versionName ?: "?" }
        catch (_: Throwable) { "?" }

    private fun startKernel() {
        val prefs  = getSharedPreferences(PREFS, MODE_PRIVATE)
        val nodeId = ensureNodeId(prefs)
        val host   = prefs.getString(PREF_RELAY_HOST, "") ?: ""
        val port   = prefs.getInt(PREF_RELAY_PORT, 7400)
        val key    = prefs.getString(PREF_RELAY_KEY, "") ?: ""
        startKernelWith(nodeId, host, port, key)
    }

    private fun startKernelWith(nodeId: Int, host: String, port: Int, key: String) {
        val intent = Intent(this, PKernelService::class.java).apply {
            putExtra(PKernelService.EXTRA_NODE_ID,    nodeId)
            putExtra(PKernelService.EXTRA_RELAY_HOST, host)
            putExtra(PKernelService.EXTRA_RELAY_PORT, port)
            putExtra(PKernelService.EXTRA_RELAY_KEY,  key)
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            startForegroundService(intent)
        } else {
            startService(intent)
        }
    }

    private fun stopKernel() {
        /* relight-fix: this is the owner DELIBERATELY putting the star to sleep
         * (眠らせる). Record it as an explicit choice BEFORE stopService(), so the
         * galaxy splash can truthfully offer 灯す instead of inferring "asleep"
         * from a dead port (which misclassifies a slow cold boot). bootKernelOnce
         * clears the flag again the next time the star actually lights. */
        getSharedPreferences(PREFS, MODE_PRIVATE).edit()
            .putBoolean(PKernelService.PREF_SLEPT_BY_CHOICE, true).apply()
        stopService(Intent(this, PKernelService::class.java))
    }

    /* galaxy.md D4: open the observation window. The galaxy port follows the
     * node id (7800 + node_id - 1), so pass the same id the service booted. */
    private fun openGalaxy() {
        startActivity(Intent(this, GalaxyActivity::class.java).apply {
            putExtra(GalaxyActivity.EXTRA_NODE_ID, currentNodeId())
        })
    }

    /* "View introduction again": open the galaxy and replay the picture-book
     * intro (pictures only, no re-consent — EXTRA_SHOW_INTRO -> ?intro=1 ->
     * introOpen(false) in galaxy.html). For a returning, already-consented
     * user who wants to re-read the welcome. */
    private fun replayIntro() {
        startActivity(Intent(this, GalaxyActivity::class.java).apply {
            putExtra(GalaxyActivity.EXTRA_NODE_ID, currentNodeId())
            putExtra(GalaxyActivity.EXTRA_SHOW_INTRO, true)
        })
    }

    companion object {
        const val EXTRA_ADVANCED = "advanced"
        private const val PREFS = "ump"
        // Battery-floor SeekBar range (10..50, step 5 -> 9 stops, SeekBar max=8).
        private const val FLOOR_MIN = 10
        private const val FLOOR_MAX = 50
        private const val FLOOR_STEP = 5
        private const val PREF_NODE_ID = "node_id"
        // N-0: a per-install RANDOM secret (hex), minted once and persisted.
        // The node id is DERIVED from it (sha256 -> [1..63]) so two fresh
        // installs reliably get DISTINCT, STABLE ids instead of both being 1
        // (which makes SWIM self-echo-filter them and never mesh). The old
        // Math.random()*60 was weak and not a real per-install secret.
        // Honest bound: 63 usable ids -> a hash collision is possible for a
        // large fleet; true uniqueness needs the key-derived / Ed25519 id (a
        // named future wave). Reliable for 2-3 phones.
        private const val PREF_NODE_SEED = "node_seed"
        private const val DNODE_MAX = 64

        /** Mint (once) a persistent random per-install seed and derive a
         *  STABLE node id in [1..DNODE_MAX-1] from it. Idempotent: the same
         *  install always returns the same id. Persists BOTH the seed and the
         *  derived id into "ump" prefs. */
        fun ensureNodeId(prefs: android.content.SharedPreferences): Int {
            // honour an already-derived id (also lets the engineer page pin one).
            val existing = prefs.getInt(PREF_NODE_ID, 0)
            if (existing in 1 until DNODE_MAX) return existing

            val stored = prefs.getString(PREF_NODE_SEED, null)
            val seedHex: String = if (!stored.isNullOrEmpty()) {
                stored
            } else {
                val seed = ByteArray(16)
                java.security.SecureRandom().nextBytes(seed)
                val hex = seed.joinToString("") { "%02x".format(it) }
                prefs.edit().putString(PREF_NODE_SEED, hex).apply()
                hex
            }
            val id = nodeIdFromSeedHex(seedHex)
            prefs.edit().putInt(PREF_NODE_ID, id).apply()
            return id
        }

        /** sha256(seed) -> first 4 bytes -> [1..DNODE_MAX-1]. Mirrors
         *  arch/linux/node_id.c::digest_to_id so the Kotlin-passed id and the
         *  native seed-file path agree on the derivation. */
        fun nodeIdFromSeedHex(seedHex: String): Int {
            val seed = ByteArray(seedHex.length / 2) {
                seedHex.substring(it * 2, it * 2 + 2).toInt(16).toByte()
            }
            val d = java.security.MessageDigest.getInstance("SHA-256").digest(seed)
            val v = ((d[0].toLong() and 0xff) shl 24) or
                    ((d[1].toLong() and 0xff) shl 16) or
                    ((d[2].toLong() and 0xff) shl 8) or
                    (d[3].toLong() and 0xff)
            return (v % (DNODE_MAX - 1L)).toInt() + 1   // 1..63
        }

        private const val PREF_RELAY_HOST = "relay_host"
        private const val PREF_RELAY_PORT = "relay_port"
        private const val PREF_RELAY_KEY = "relay_key"
        // GPU enable flag (gpu-ui wave). Default OFF; mirrors the native
        // gpu_set_enabled default + it's honestly experimental.
        const val PREF_USE_GPU = "use_gpu"
    }

    private fun ensureNotificationChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val nm = getSystemService(NotificationManager::class.java)
            val ch = NotificationChannel(
                PKernelService.CHANNEL_ID,
                getString(R.string.notif_channel_name),
                NotificationManager.IMPORTANCE_LOW
            ).apply {
                description = getString(R.string.notif_channel_desc)
                setShowBadge(false)
            }
            nm?.createNotificationChannel(ch)
        }
    }
}
