/*
 * MainActivity.kt — UMP entry screen (i18n + ワクワク wave).
 *
 * The screen now leads with a StarfieldView backdrop, the project name, a
 * localized tagline (the device-language manifesto line 3, human-approved),
 * and a single hero button ("Shine" / 光れ). A first-time user taps that one
 * button to light their OWN star — solo works with no relay.
 *
 * The relay host/port/key fields still exist (Intent extras to
 * PKernelService are UNCHANGED), but live in a collapsed "Advanced — join a
 * fleet" group that expands on tap. All visible strings come from
 * values-<locale>/strings.xml (generated by tools/android/gen_strings.py for
 * the 32 manifesto languages), so the screen speaks the user's language from
 * the first frame, falling back to English for any unlisted locale.
 *
 * A TextView at the bottom tail-streams the kernel's stdout.
 */

package io.pkernel

import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Intent
import android.os.Build
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.text.method.ScrollingMovementMethod
import android.view.View
import android.widget.Button
import android.widget.EditText
import android.widget.LinearLayout
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {

    private lateinit var nodeIdField: EditText
    private lateinit var relayHostField: EditText
    private lateinit var relayPortField: EditText
    private lateinit var relayKeyField: EditText
    private lateinit var advancedGroup: LinearLayout
    private lateinit var logView: TextView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        ensureNotificationChannel()

        nodeIdField    = findViewById(R.id.field_node_id)
        relayHostField = findViewById(R.id.field_relay_host)
        relayPortField = findViewById(R.id.field_relay_port)
        relayKeyField  = findViewById(R.id.field_relay_key)
        advancedGroup  = findViewById(R.id.advanced_group)
        logView        = findViewById(R.id.log_view)
        logView.movementMethod = ScrollingMovementMethod()

        findViewById<Button>(R.id.btn_start ).setOnClickListener { startKernel() }
        findViewById<Button>(R.id.btn_stop  ).setOnClickListener { stopKernel()  }
        findViewById<Button>(R.id.btn_galaxy).setOnClickListener { openGalaxy()  }

        /* "Advanced — join a fleet": reveal the relay fields on tap. Solo is
         * the default; the relay is opt-in. */
        findViewById<TextView>(R.id.advanced_toggle).setOnClickListener {
            advancedGroup.visibility =
                if (advancedGroup.visibility == View.VISIBLE) View.GONE else View.VISIBLE
        }

        /* Pull the service's tail-log every 250 ms while we're foregrounded. */
        val handler = Handler(Looper.getMainLooper())
        handler.post(object : Runnable {
            override fun run() {
                val tail = PKernelService.drainLog()
                if (tail.isNotEmpty()) {
                    logView.append(tail)
                    /* Auto-scroll to the bottom. */
                    val scrollAmount = logView.layout?.getLineTop(logView.lineCount)?.minus(logView.height) ?: 0
                    if (scrollAmount > 0) logView.scrollTo(0, scrollAmount)
                }
                handler.postDelayed(this, 250)
            }
        })
    }

    private fun startKernel() {
        val intent = Intent(this, PKernelService::class.java).apply {
            putExtra(PKernelService.EXTRA_NODE_ID,    nodeIdField.text.toString().toIntOrNull() ?: 1)
            putExtra(PKernelService.EXTRA_RELAY_HOST, relayHostField.text.toString().trim())
            putExtra(PKernelService.EXTRA_RELAY_PORT, relayPortField.text.toString().toIntOrNull() ?: 7400)
            putExtra(PKernelService.EXTRA_RELAY_KEY,  relayKeyField.text.toString().trim())
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            startForegroundService(intent)
        } else {
            startService(intent)
        }
    }

    private fun stopKernel() {
        stopService(Intent(this, PKernelService::class.java))
    }

    /* galaxy.md D4: open the observation window. The galaxy port follows the
     * node id (7800 + node_id - 1), so pass the same id the service booted. */
    private fun openGalaxy() {
        val nodeId = nodeIdField.text.toString().toIntOrNull() ?: 1
        startActivity(Intent(this, GalaxyActivity::class.java).apply {
            putExtra(GalaxyActivity.EXTRA_NODE_ID, nodeId)
        })
    }

    private fun ensureNotificationChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val nm = getSystemService(NotificationManager::class.java)
            val ch = NotificationChannel(
                PKernelService.CHANNEL_ID,
                getString(R.string.notif_channel_name),
                NotificationManager.IMPORTANCE_LOW
            ).apply {
                description = getString(R.string.notif_channel_desc)
                setShowBadge(false)
            }
            nm?.createNotificationChannel(ch)
        }
    }
}
