# embed_spv.cmake — compile a GLSL compute shader to SPIR-V and embed the
# words as a C header, at build time. Run via `cmake -P` from the CMakeLists
# custom command. No runtime shader compiler is shipped; only these bytes.
#
# Inputs (set with -D on the cmake -P line):
#   GLSLC    : path to glslc (NDK shader-tools)
#   SRC      : the .comp shader source
#   OUT      : the header to write (e.g. matmul_f32_spv.h)
#   SYM      : the C symbol base name (e.g. matmul_f32_spv)
#
# Emits:  static const uint32_t <SYM>[]   and   <SYM>_len  (size in BYTES).

if(NOT GLSLC OR NOT SRC OR NOT OUT OR NOT SYM)
    message(FATAL_ERROR "embed_spv.cmake: GLSLC/SRC/OUT/SYM all required")
endif()

# glslc -mfmt=num prints comma-separated 0x........ uint32 words to stdout.
execute_process(
    COMMAND "${GLSLC}" -fshader-stage=comp -O -mfmt=num "${SRC}" -o -
    OUTPUT_VARIABLE SPV_WORDS
    RESULT_VARIABLE  RC
    ERROR_VARIABLE   ERR)
if(NOT RC EQUAL 0)
    message(FATAL_ERROR "glslc failed (${RC}) on ${SRC}:\n${ERR}")
endif()

# Strip whitespace/newlines; count the words to compute the byte length.
string(REGEX MATCHALL "0x[0-9a-fA-F]+" WORDLIST "${SPV_WORDS}")
list(LENGTH WORDLIST NWORDS)
if(NWORDS LESS 5)
    message(FATAL_ERROR "glslc produced too few SPIR-V words (${NWORDS})")
endif()
math(EXPR NBYTES "${NWORDS} * 4")
string(JOIN ",\n    " JOINED ${WORDLIST})

file(WRITE "${OUT}"
"/* AUTO-GENERATED by embed_spv.cmake from ${SRC} — DO NOT EDIT.\n"
" * SPIR-V for the GPU-1 compute shader, embedded so no runtime shader\n"
" * compiler ships. Regenerate by re-running the Android CMake build. */\n"
"#ifndef PK_${SYM}_H\n"
"#define PK_${SYM}_H\n"
"#include <stdint.h>\n"
"static const uint32_t ${SYM}[] = {\n    ${JOINED}\n};\n"
"static const uint32_t ${SYM}_len = ${NBYTES}; /* bytes */\n"
"#endif\n")

message(STATUS "embed_spv: ${SRC} -> ${OUT}  (${NWORDS} words, ${NBYTES} bytes)")
