#!/usr/bin/env python3
# gen_page.py — galaxy.md D3: convert the committed galaxy.html into a C
# array (galaxy_page.h) at BUILD time, so the embedded page can never
# drift from source and embedding can never fail at runtime.
#   usage: gen_page.py <galaxy.html> <galaxy_page.h>
import sys

def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: gen_page.py <in.html> <out.h>\n")
        return 1
    data = open(sys.argv[1], "rb").read()
    out = []
    out.append("/* GENERATED by tools/galaxy/gen_page.py from "
               "arch/common/web/galaxy.html — DO NOT EDIT. */\n")
    out.append("#pragma once\n")
    out.append("static const unsigned char galaxy_page[] = {\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        out.append("    " + ",".join(str(b) for b in chunk) + ",\n")
    out.append("};\n")
    out.append("static const unsigned int galaxy_page_len = %d;\n" % len(data))
    open(sys.argv[2], "w").write("".join(out))
    return 0

if __name__ == "__main__":
    sys.exit(main())
