#!/usr/bin/env python3
# gen_page.py — galaxy.md D3: convert a committed web asset into a C array
# at BUILD time, so the embedded bytes can never drift from source and
# embedding can never fail at runtime.
#   usage: gen_page.py <in> <out.h> [symbol]
# symbol defaults to "galaxy_page"; ark-profile passes "manifesto" so the
# same pipeline embeds arch/common/web/manifesto.txt -> manifesto_page.h.
import sys

def main():
    if len(sys.argv) not in (3, 4):
        sys.stderr.write("usage: gen_page.py <in> <out.h> [symbol]\n")
        return 1
    sym = sys.argv[3] if len(sys.argv) == 4 else "galaxy_page"
    data = open(sys.argv[1], "rb").read()
    out = []
    out.append("/* GENERATED by tools/galaxy/gen_page.py from "
               + sys.argv[1] + " — DO NOT EDIT. */\n")
    out.append("#pragma once\n")
    out.append("static const unsigned char %s[] = {\n" % sym)
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        out.append("    " + ",".join(str(b) for b in chunk) + ",\n")
    out.append("};\n")
    out.append("static const unsigned int %s_len = %d;\n" % (sym, len(data)))
    open(sys.argv[2], "w").write("".join(out))
    return 0

if __name__ == "__main__":
    sys.exit(main())
