#!/usr/bin/env python3
# gen_manifestos.py — i18n wave: embed N manifesto translations into ONE
# generated header as per-language byte arrays + a manifesto_table[] of
# {code, endonym, bytes, len}. The content-id of each version is computed
# AT RUNTIME by ark_profile.c via pfs_id_compute (the ONE hash) — we do NOT
# precompute sha256 here, so the id can never drift from the served bytes.
#
#   usage: gen_manifestos.py <out.h> <code:endonym:file> [<code:endonym:file> ...]
#
# The FIRST entry is the canonical/default (ja). Build wiring decides which
# languages to pass: hosted passes all ~32; bare-metal passes only ja+en
# (no web UI there; lean kernel — the manifesto is for the future
# netstack-tcp-server slice). See ark-profile.md §7.5.
import sys

def emit_array(out, sym, data):
    out.append("static const unsigned char %s[] = {\n" % sym)
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        out.append("    " + ",".join(str(b) for b in chunk) + ",\n")
    out.append("};\n")

def main():
    if len(sys.argv) < 3:
        sys.stderr.write("usage: gen_manifestos.py <out.h> <code:endonym:file> ...\n")
        return 1
    outpath = sys.argv[1]
    specs = sys.argv[2:]
    out = []
    out.append("/* GENERATED by tools/galaxy/gen_manifestos.py — DO NOT EDIT. */\n")
    out.append("#pragma once\n")

    entries = []
    for n, spec in enumerate(specs):
        # split on ':' but only twice (endonym/file never contain ':' here)
        code, endonym, path = spec.split(":", 2)
        data = open(path, "rb").read()
        sym = "manifesto_%d" % n
        emit_array(out, sym, data)
        entries.append((code, endonym, sym, len(data)))

    # the canonical bytes (entry 0) are ALSO exposed as `manifesto`/`manifesto_len`
    # so ark_profile.c's existing ark_manifesto_bytes()/id() stay byte-identical.
    out.append("static const unsigned char *const manifesto = manifesto_0;\n")
    out.append("static const unsigned int manifesto_len = %d;\n" % entries[0][3])

    out.append("typedef struct { const char *code; const char *endonym;\n")
    out.append("                 const unsigned char *bytes; unsigned int len; }\n")
    out.append("        MANIFESTO_ROW;\n")
    out.append("static const MANIFESTO_ROW manifesto_table[] = {\n")
    for code, endonym, sym, ln in entries:
        # endonym is a UTF-8 literal; emit as a C string (escape backslash/quote)
        esc = endonym.replace("\\", "\\\\").replace('"', '\\"')
        out.append('    { "%s", "%s", %s, %d },\n' % (code, esc, sym, ln))
    out.append("};\n")
    out.append("static const unsigned int manifesto_count = %d;\n" % len(entries))
    open(outpath, "w").write("".join(out))
    return 0

if __name__ == "__main__":
    sys.exit(main())
